index:
  path: /
  controller: App\Controller\DefaultController::index

contact:
  path: /contact
  controller: App\Controller\DefaultController::contact

boutique:
  path: /boutique
  controller: App\Controller\BoutiqueController::index

rayon:
  path: /boutique/rayon/{idCategorie}
  controller: App\Controller\BoutiqueController::rayon

panier:
  path: /panier
  controller: App\Controller\PanierController::index

panier_ajouter:
  path: /panier/ajouter/{idProduit}/{quantite}
  controller: App\Controller\PanierController::ajouter
  defaults:
    quantite : '1'

panier_enlever:
  path: /panier/enlever/{idProduit}/{quantite}
  controller: App\Controller\PanierController::enlever
  defaults:
    quantite: '1'

panier_supprimer:
  path: /panier/supprimer/{idProduit}
  controller: App\Controller\PanierController::supprimer

panier_vider:
  path: /panier/vider
  controller: App\Controller\PanierController::vider

panier_valider:
  path: /panier/valider
  controller: App\Controller\PanierController::valider

usager_index:
  path: /usager
  controller: App\Controller\UsagerController::index

usager_new:
  path: /usager/new
  controller: App\Controller\UsagerController::new

usager_orders:
  path: /usager/commandes
  controller: App\Controller\UsagerController::commandes

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

login:
  path: /login
  controller: App\Controller\SecurityController::login













