index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

contact:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  requirements:
    _locale: '%app.supported_locales%'

boutique:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController::index
  requirements:
    _locale: '%app.supported_locales%'

rayon:
  path: /{_locale}/boutique/rayon/{idCategorie}
  controller: App\Controller\BoutiqueController::rayon
  requirements:
    _locale: '%app.supported_locales%'

panier:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::index
  requirements:
    _locale: '%app.supported_locales%'

panier_ajouter:
  path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
  controller: App\Controller\PanierController::ajouter
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    quantite : '1'

panier_enlever:
  path: /{_locale}/panier/enlever/{idProduit}/{quantite}
  controller: App\Controller\PanierController::enlever
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    quantite: '1'

panier_supprimer:
  path: /{_locale}/panier/supprimer/{idProduit}
  controller: App\Controller\PanierController::supprimer
  requirements:
    _locale: '%app.supported_locales%'

panier_vider:
  path: /{_locale}/panier/vider
  controller: App\Controller\PanierController::vider
  requirements:
    _locale: '%app.supported_locales%'

panier_valider:
  path: /{_locale}/panier/valider
  controller: App\Controller\PanierController::valider
  requirements:
    _locale: '%app.supported_locales%'

usager_index:
  path: /{_locale}/usager
  controller: App\Controller\UsagerController::index
  requirements:
    _locale: '%app.supported_locales%'

usager_new:
  path: /{_locale}/usager/new
  controller: App\Controller\UsagerController::new
  requirements:
    _locale: '%app.supported_locales%'

usager_orders:
  path: /{_locale}/usager/commandes
  controller: App\Controller\UsagerController::commandes
  requirements:
    _locale: '%app.supported_locales%'

app_login:
  path: /{_locale}/login
  controller: App\Controller\SecurityController::login
  requirements:
    _locale: '%app.supported_locales%'

app_logout:
  path: /{_locale}/logout
  controller: App\Controller\SecurityController::logout
  requirements:
    _locale: '%app.supported_locales%'














